export const LOAD_ALL_PRESENTATION = "LOAD_ALL_PRESENTATION";
export const LOAD_PRESENTATION = "LOAD_PRESENTATION";
export const ADD_PRESENTATION = "ADD_PRESENTATION";
export const ADD_ATTENDEE_TO_PRESENTATION = "ADD_ATTENDEE_TO_PRESENTATION";
export const UPDATE_PRESENTATION = "LOAD_PRESENTATION";
